function(add_gossip_test label binary source)
    if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${source})
        return()
    endif()
    add_executable(${binary} ${source})
    target_include_directories(${binary} PRIVATE ${PROJECT_SOURCE_DIR}/tests/tests_common ${PROJECT_SOURCE_DIR}/src)
    target_link_libraries(${binary} PRIVATE streamrtps_mock pthread)
    configure_static_example(${binary})
    set(_timeout 120)
    if(label STREQUAL "soak")
        set(_timeout 1800)
    elseif(label STREQUAL "e2e")
        set(_timeout 300)
    endif()
    foreach(t ${ARGN})
        add_test(NAME ${label}_${t} COMMAND ${binary} ${t})
        set_tests_properties(${label}_${t} PROPERTIES LABELS ${label} TIMEOUT ${_timeout})
    endforeach()
endfunction()
